security:    
    encoders:
        Acme\UserBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: true
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: AcmeUserBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        admin_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check                
                default_target_path: /admin
            logout:
                path:   /logout
                target: /login
                invalidate_session: false

    access_control:
        - { path: ^/admin, roles: ROLE_USER }